version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "juno/builder/"
    schedule:
      interval: "monthly"
    groups:
      py-deps:
        patterns:
          - "*"
